### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 30000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "4f6abe9c64c74c31ad84612a1e3b038f",
  "accountNumber": "1000000000",
  "amount": 30000
}

### query transaction
GET http://localhost:8080/transaction/680d3f34874b4c78a817f6eebc0d0126