# h2 console 접속 주소 : http://localhost:8080/h2-console
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  # h2.console.enabled: true  =  ?????? ?? ??? ????
  h2:
    console:
      enabled: true

  # defer-datasource-initialization: true = ??? ??? ??? ? ??? ?? ? ??? ? ??? ???
  # hibernate.ddl-auto: create-drop  = ?????? ?? ? ???? ?????, ?????? ?? ? ???? ???? _ ??? ????? ???? ??
  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

